path: "_secrets"
default: # default is dev/testing values
  secrets:
    - ".env"
    - "app/src/main/res/values/env.xml"
    - "app/google-services.json"
sets:
  ci:
    path: "_ci"
    secrets:
      - "keystores/upload.keystore"
      - "fastlane/fastlane_google_service_account.json"
      - "fastlane/firebase_testlab_google_service_account.json"
  production:
    path: "_production"