sudo: false
language: android
jdk:
  - oraclejdk8

install:
  - bundle install --path vendor/bundle
before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/
cache:
  directories:
    # Android SDK
    - $HOME/android-sdk-dl
    - $HOME/android-sdk

    # Gradle dependencies
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/

    # Gems
    - vendor/bundle

    # Android build cache (see http://tools.android.com/tech-docs/build-cache)
    - $HOME/.android/build-cache
env:
  - ANDROID_HOME=$HOME/android-sdk

jobs:
  include:
    - stage: danger
      script: bundle exec danger --fail-on-errors=true
    - stage: beta-release
      script: ./bin/install_android_sdk.sh && ./gradlew androidDependencies && bundle exec fastlane beta
    - stage: prod-release
      script: ./bin/install_android_sdk.sh && ./gradlew androidDependencies && bundle exec fastlane production

stages:
  - name: danger
    if: type IN (pull_request)
  - name: beta-release
    if: branch = beta AND type IN (pull_request)
  - name: prod-release
    if: branch = production AND type IN (pull_request)
